package com.safict.recogeme;

import android.app.Activity;
import android.app.AlertDialog;
import android.app.Notification;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.DialogInterface;
import android.content.Intent;
import android.os.Bundle;
import android.os.StrictMode;
import android.util.Log;
import android.view.KeyEvent;
import android.view.MotionEvent;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

/**
 * Created by Elkin on 6/13/2015.
 */
public class formulario extends Activity implements View.OnClickListener, View.OnTouchListener {

    NotificationManager notificacion_Pendiente;
    private static final int ID_Notif_Pendiente = 1;

    public static boolean touchDireccion = false;
    public static boolean touchNombre = false;
    public static boolean touchTelefono = false;
    public static boolean touchPeso = false;
    public TextView tvCiudad;
    public TextView tvDireccion;
    public TextView tvNombre;
    public TextView tvTelefono;
    public String SeleccionTipoEnvio;
    public String SeleccionCiudadDestino;
    public TextView tvPeso;
    public boolean seleccionTipoEnvio = false;
    public boolean seleccionDestino = false;

    HttpHandler handler = new HttpHandler("http://recogeme.safict.com/API/post_Service.php");

    public Spinner tipoEnvio;
    public Spinner ciudadDestino;
    String[] arraytipoEnvio = {"Seleccione tipo Envio:", "Sobre de Carta", "Sobre de Manila", "Paquete MENOR a 5 Kilos", "Paquete MENOR 5 Kilos", "Tula", "Caja MAYOR a 5 Kilos", "Bulto", "Otros"};
    String[] arrayCiudadDestino = {"Seleccione Destino:","BOGOTA-CUNDINAMARCA", "ABEJORRAL-ANTIOQUIA", "ABREGO-NORTE DE SANTANDER", "ABRIAQUI-ANTIOQUIA", "ACACIAS-META", "ACANDI-CHOCO", "ACEVEDO-HUILA", "ACHI-BOLIVAR", "AGRADO-HUILA", "AGUA DE DIOS-CUNDINAMARCA", "AGUACHICA-CESAR", "AGUADA-SANTANDER", "AGUADAS-CALDAS", "AGUAZUL-CASANARE", "AGUSTIN CODAZZI-CESAR", "AIPE-HUILA", "ALBAN CUNDINAMARCA-CUNDINAMARCA", "ALBAN NARINO-NARINO", "ALBANIA CAQUETA-CAQUETA", "ALBANIA GUAJIRA-GUAJIRA", "ALBANIA SANTANDER-SANTANDER", "ALCALA-VALLE DEL CAUCA", "ALDANA-NARINO", "ALEJANDRIA-ANTIOQUIA", "ALGECIRAS-HUILA", "ALMAGUER-CAUCA", "ALMEIDA-BOYACA", "ALPUJARRA-TOLIMA", "ALTAMIRA BETULIA-ANTIOQUIA", "ALTAMIRA HUILA-HUILA", "ALTO BAUDO-CHOCO", "ALTOS DEL ROSARIO-BOLIVAR", "ALVARADO-TOLIMA", "AMAGA-ANTIOQUIA", "AMALFI-ANTIOQUIA", "AMBALEMA-TOLIMA", "ANAPOIMA-CUNDINAMARCA", "ANCUYA-NARINO", "ANDALUCIA-VALLE DEL CAUCA", "ANDES-ANTIOQUIA", "ANGELOPOLIS-ANTIOQUIA", "ANGOSTURA-ANTIOQUIA", "ANOLAIMA-CUNDINAMARCA", "ANORI-ANTIOQUIA", "ANSERMA-CALDAS", "ANSERMANUEVO-VALLE DEL CAUCA", "ANZA-ANTIOQUIA", "ANZOATEGUI-TOLIMA", "APARTADO-ANTIOQUIA", "APIA-RISALDA", "APULO-CUNDINAMARCA", "AQUITANIA-BOYACA", "ARACATACA-MAGDALENA", "ARANZAZU-CALDAS", "ARATOCA-SANTANDER", "ARAUCA ARAUCA-ARAUCA", "ARAUCA PALESTINA-CALDAS", "ARAUQUITA-ARAUCA", "ARBELAEZ-CUNDINAMARCA", "ARBOLEDA BERRUECOS-NARINO", "ARBOLEDAS-NORTE DE SANTANDER", "ARBOLETES-ANTIOQUIA", "ARCABUCO-BOYACA", "ARENAL-BOLIVAR", "ARGELIA ANTIOQUIA-ANTIOQUIA", "ARGELIA CAUCA-CAUCA", "ARGELIA VALLE DEL CAUCA-VALLE DEL CAUCA", "ARIGUANI-MAGDALENA", "ARJONA-BOLIVAR", "ARMENIA_ANTIOQUIA-ANTIOQUIA", "ARMENIA_QUINDIO-QUINDIO", "ARMERO-TOLIMA", "ARROYOHONDO-BOLIVAR", "ASTREA-CESAR", "ATACO-TOLIMA", "ATRATO-CHOCO", "AYAPEL-CORDOBA", "BAGADO-CHOCO", "BAHIA SOLANO-CHOCO", "BAJO BAUDO-CHOCO", "BALBOA CAUCA-CAUCA", "BALBOA RISARALDA-RISALDA", "BARANOA-ATLANTICO", "BARAYA-HUILA", "BARBACOAS-NARINO", "BARBOSA ANTIOQUIA-ANTIOQUIA", "BARBOSA SANTANDER-SANTANDER", "BARICHARA-SANTANDER", "BARRANCA DE UPIA-META", "BARRANCABERMEJA-SANTANDER", "BARRANCAS-GUAJIRA", "BARRANCO DE LOBA-BOLIVAR", "BARRANCO MINAS-GUAINIA", "BARRANQUILLA-ATLANTICO", "BECERRIL-CESAR", "BELALCAZAR-CALDAS", "BELEN BOYACA-BOYACA", "BELEN DE BAJIRA-CHOCO", "BELEN DE LOS ANDAQUIES-CAQUETA", "BELEN DE UMBRIA-RISALDA", "BELEN NARINO-NARINO", "BELLO-ANTIOQUIA", "BELMIRA-ANTIOQUIA", "BELTRAN-CUNDINAMARCA", "BERBEO-BOYACA", "BETANIA-ANTIOQUIA", "BETEITIVA-BOYACA", "BETULIA ANTIOQUIA-ANTIOQUIA", "BETULIA SANTANDER-SANTANDER", "BITUIMA-CUNDINAMARCA", "BOAVITA-BOYACA", "BOCAS DE SATINGA(OLAYA HERRERA)-NARINO", "BOCHALEMA-NORTE DE SANTANDER", "BOGOTA-CUNDINAMARCA", "BOJACA-CUNDINAMARCA", "BOJAYA-CHOCO", "BOLIVAR CAUCA-CAUCA", "BOLIVAR SANTANDER-SANTANDER", "BOLIVAR VALLE DEL CAUCA-VALLE DEL CAUCA", "BOLIVIA-CALDAS", "BOSCONIA-CESAR", "BOYACA-BOYACA", "BRICENO ANTIOQUIA-ANTIOQUIA", "BRICENO BOYACA-BOYACA", "BRICENO TOCANCIPA-CUNDINAMARCA", "BUCARAMANGA-SANTANDER", "BUCARASICA-NORTE DE SANTANDER", "BUENAVENTURA-VALLE DEL CAUCA", "BUENAVISTA BOYACA-BOYACA", "BUENAVISTA CORDOBA-CORDOBA", "BUENAVISTA QUINDIO-QUINDIO", "BUENAVISTA SUCRE-SUCRE", "BUENOS AIRES-CAUCA", "BUESACO-NARINO", "BUGA-VALLE DEL CAUCA", "BUGALAGRANDE-VALLE DEL CAUCA", "BURITICA-ANTIOQUIA", "BUSBANZA-BOYACA", "CABRERA CUNDINAMARCA-CUNDINAMARCA", "CABRERA SANTANDER-SANTANDER", "CABUYARO-META", "CACHIPAY-CUNDINAMARCA", "CACHIRA-NORTE DE SANTANDER", "CACOTA-NORTE DE SANTANDER", "CAICEDO-ANTIOQUIA", "CAICEDONIA-VALLE DEL CAUCA", "CAIMITO-SUCRE", "CAJAMARCA-TOLIMA", "CAJIBIO-CAUCA", "CAJICA-CUNDINAMARCA", "CALAMAR BOLIVAR-BOLIVAR", "CALAMAR GUAVIARE-GUAVIARE", "CALARCA-QUINDIO", "CALDAS ANTIOQUIA-ANTIOQUIA", "CALDAS BOYACA-BOYACA", "CALDONO-CAUCA", "CALI-VALLE DEL CAUCA", "CALIFORNIA-SANTANDER", "CALIMA DARIEN-VALLE DEL CAUCA", "CALOTO-CAUCA", "CAMBAO-SAN-CUNDINAMARCA", "CAMPAMENTO-ANTIOQUIA", "CAMPO DE LA CRUZ-ATLANTICO", "CAMPOALEGRE-HUILA", "CAMPOHERMOSO-BOYACA", "CANALETE-CORDOBA", "CANASGORDAS-ANTIOQUIA", "CANDELARIA VALLE DEL CAUCA-VALLE DEL CAUCA", "CANTAGALLO-BOLIVAR", "CAPARRAPI-CUNDINAMARCA", "CAPELLANIA-CUNDINAMARCA", "CAPITANEJO-SANTANDER", "CAQUEZA-CUNDINAMARCA", "CARACOLI-ANTIOQUIA", "CARAMANTA-ANTIOQUIA", "CARCASI-SANTANDER", "CAREPA-ANTIOQUIA", "CARMEN DE APICALA-TOLIMA", "CARMEN DE CARUPA-CUNDINAMARCA", "CARMEN DEL DARIEN-CHOCO", "CAROLINA-ANTIOQUIA", "CARTAGENA BOLIVAR-BOLIVAR", "CARTAGENA DEL CHAIRA-CAQUETA", "CARTAGENA ZIPACON-CUNDINAMARCA", "CARTAGO-VALLE DEL CAUCA", "CARURU-VAUPES", "CASABIANCA-TOLIMA", "CASTILLA LA NUEVA-META", "CASTILLA-TOLIMA", "CAUCASIA-ANTIOQUIA", "CEPITA-SANTANDER", "CERETE-CORDOBA", "CERINZA-BOYACA", "CERRITO-SANTANDER", "CERRO SAN ANTONIO-MAGDALENA", "CERTEGUI-CHOCO", "CHACHAGUI-NARINO", "CHAGUANI-CUNDINAMARCA", "CHALAN-SUCRE", "CHAMEZA-CASANARE", "CHAPARRAL-TOLIMA", "CHARALA-SANTANDER", "CHARTA-SANTANDER", "CHIA-CUNDINAMARCA", "CHIBOLO-MAGDALENA", "CHICORAL-TOLIMA", "CHIFLAS-SANTANDER", "CHIGORODO-ANTIOQUIA", "CHIMA CORDOBA-CORDOBA", "CHIMA SANTANDER-SANTANDER", "CHIMICHAGUA-CESAR", "CHINACOTA-NORTE DE SANTANDER", "CHINAVITA-BOYACA", "CHINCHINA-CALDAS", "CHINU-CORDOBA", "CHIPAQUE-CUNDINAMARCA", "CHIPATA-SANTANDER", "CHIQUINQUIRA-BOYACA", "CHIQUIZA-BOYACA", "CHIRIGUANA-CESAR", "CHISCAS-BOYACA", "CHITA-BOYACA", "CHITAGA-NORTE DE SANTANDER", "CHITARAQUE-BOYACA", "CHIVATA-BOYACA", "CHIVOR-BOYACA", "CHOACHI-CUNDINAMARCA", "CHOCONTA-CUNDINAMARCA", "CICUCO-BOLIVAR", "CIENAGA DE ORO-CORDOBA", "CIENAGA-MAGDALENA", "CIENEGA-BOYACA", "CIMITARRA-SANTANDER", "CINCELADA-SANTANDER", "CIRCASIA-QUINDIO", "CISNEROS-ANTIOQUIA", "CIUDAD BOLIVAR-ANTIOQUIA", "CLEMENCIA-BOLIVAR", "COCORNA-ANTIOQUIA", "COELLO-TOLIMA", "COGUA-CUNDINAMARCA", "COLOMBIA-HUILA", "COLON NARINO-NARINO", "COLON PUTUMAYO-PUTUMAYOMAYO", "COLOSO-SUCRE", "COMBITA-BOYACA", "CONCEPCION ANTIOQUIA-ANTIOQUIA", "CONCEPCION SANTANDER-SANTANDER", "CONCORDIA ANTIOQUIA-ANTIOQUIA", "CONCORDIA MAGDALENA-MAGDALENA", "CONDOTO-CHOCO", "CONFINES-SANTANDER", "CONSACA-NARINO", "CONTADERO-NARINO", "CONTRATACION-SANTANDER", "CONVENCION-NORTE DE SANTANDER", "COPACABANA-ANTIOQUIA", "COPER-BOYACA", "CORDOBA BOLIVAR-BOLIVAR", "CORDOBA NARINO-NARINO", "CORDOBA QUINDIO-QUINDIO", "CORINTO-CAUCA", "COROMORO-SANTANDER", "COROZAL-SUCRE", "CORRALES-BOYACA", "COTA-CUNDINAMARCA", "COTORRA-CORDOBA", "COVARACHIA-BOYACA", "COVENAS-SUCRE", "COYAIMA-TOLIMA", "CRAVO NORTE-ARAUCA", "CUASPUD-NARINO", "CUBARA-BOYACA", "CUBARRAL-META", "CUCAITA-BOYACA", "CUCUNUBA-CUNDINAMARCA", "CUCUTA-NORTE DE SANTANDER", "CUCUTILLA-NORTE DE SANTANDER", "CUITIVA-BOYACA", "CUMARAL-META", "CUMARIBO-VICHADA", "CUMBAL-NARINO", "CUMBITARA-NARINO", "CUNDAY-TOLIMA", "CURILLO-CAQUETA", "CURITI-SANTANDER", "CURRULAO-ANTIOQUIA", "CURUMANI-CESAR", "DABEIBA-ANTIOQUIA", "DAGUA-VALLE DEL CAUCA", "DISTRACCION-GUAJIRA", "DOLORES-TOLIMA", "DON MATIAS-ANTIOQUIA", "DORADAL-ANTIOQUIA", "DOSQUEBRADAS-RISALDA", "DUITAMA-BOYACA", "DURANIA-NORTE DE SANTANDER", "EBEJICO-ANTIOQUIA", "EL AGUILA-VALLE DEL CAUCA", "EL BAGRE-ANTIOQUIA", "EL BANCO-MAGDALENA", "EL BORDO PATIA-CAUCA", "EL CAIRO-VALLE DEL CAUCA", "EL CALVARIO-META", "EL CANTON DEL SAN PABLO-CHOCO", "EL CARMEN DE ATRATO-CHOCO", "EL CARMEN DE BOLIVAR-BOLIVAR", "EL CARMEN DE CHUCURI-SANTANDER", "EL CARMEN DE VIBORAL-ANTIOQUIA", "EL CARMEN-NORTE DE SANTANDER", "EL CASTILLO-META", "EL CERRITO-VALLE DEL CAUCA", "EL CHARCO-NARINO", "EL COCUY-BOYACA", "EL COLEGIO-CUNDINAMARCA", "EL COPEY-CESAR", "EL DONCELLO-CAQUETA", "EL DORADO-META", "EL DOVIO-VALLE DEL CAUCA", "EL ESPINO-BOYACA", "EL GUACAMAYO-SANTANDER", "EL GUAMO-BOLIVAR", "EL MOLINO-GUAJIRA", "EL PASO-CESAR", "EL PAUJIL-CAQUETA", "EL PENOL-NARINO", "EL PENON BOLIVAR-BOLIVAR", "EL PENON CUNDINAMARCA-CUNDINAMARCA", "EL PENON SANTANDER-SANTANDER", "EL PITAL-HUILA", "EL PLAYON-SANTANDER", "EL RETORNO-GUAVIARE", "EL ROBLE-SUCRE", "EL ROSAL-CUNDINAMARCA", "EL ROSARIO-NARINO", "EL SANTUARIO-ANTIOQUIA", "EL TABLON DE GOMEZ-NARINO", "EL TAMBO CAUCA-CAUCA", "EL TAMBO NARINO-NARINO", "EL TARRA-NORTE DE SANTANDER", "EL ZULIA-NORTE DE SANTANDER", "ELIAS-HUILA", "ENCINO-SANTANDER", "ENCISO-SANTANDER", "ENTRERRIOS-ANTIOQUIA", "ENVIGADO-ANTIOQUIA", "ESPINAL-TOLIMA", "FACATATIVA-CUNDINAMARCA", "FALAN-TOLIMA", "FILADELFIA-CALDAS", "FILANDIA-QUINDIO", "FIRAVITOBA-BOYACA", "FLANDES-TOLIMA", "FLORENCIA CALDAS-CALDAS", "FLORENCIA CAQUETA-CAQUETA", "FLORENCIA CAUCA-CAUCA", "FLORESTA-BOYACA", "FLORIAN-SANTANDER", "FLORIDA-VALLE DEL CAUCA", "FLORIDABLANCA-SANTANDER", "FOMEQUE-CUNDINAMARCA", "FONSECA-GUAJIRA", "FORTUL-ARAUCA", "FOSCA-CUNDINAMARCA", "FRANCISCO PIZARRO-NARINO", "FREDONIA-ANTIOQUIA", "FRESNO-TOLIMA", "FRONTINO-ANTIOQUIA", "FUENTE DE ORO-META", "FUNDACION-MAGDALENA", "FUNES-NARINO", "FUNZA-CUNDINAMARCA", "FUQUENE-CUNDINAMARCA", "FUSAGASUGA-CUNDINAMARCA", "GACHALA-CUNDINAMARCA", "GACHANCIPA-CUNDINAMARCA", "GACHANTIVA-BOYACA", "GACHETA-CUNDINAMARCA", "GAITANIA-TOLIMA", "GALAN-SANTANDER", "GALAPA-ATLANTICO", "GALERAS-SUCRE", "GAMA-CUNDINAMARCA", "GAMARRA-CESAR", "GAMBITA-SANTANDER", "GAMEZA-BOYACA", "GARAGOA-BOYACA", "GARZON-HUILA", "GENOVA-QUINDIO", "GIGANTE-HUILA", "GINEBRA-VALLE DEL CAUCA", "GIRALDO-ANTIOQUIA", "GIRARDOT-CUNDINAMARCA", "GIRARDOTA-ANTIOQUIA", "GIRON-SANTANDER", "GOMEZ PLATA-ANTIOQUIA", "GONZALEZ-CESAR", "GRANADA ANTIOQUIA-ANTIOQUIA", "GRANADA CUNDINAMARCA-CUNDINAMARCA", "GRANADA META-META", "GUACA-SANTANDER", "GUACAMAYAS-BOYACA", "GUACARI-VALLE DEL CAUCA", "GUACHENE-CAUCA", "GUACHETA-CUNDINAMARCA", "GUACHUCAL-NARINO", "GUADALUPE ANTIOQUIA-ANTIOQUIA", "GUADALUPE HUILA-HUILA", "GUADALUPE SANTANDER-SANTANDER", "GUADUAS-CUNDINAMARCA", "GUAITARILLA-NARINO", "GUALANDAY-TOLIMA", "GUALMATAN-NARINO", "GUAMAL MAGDALENA-MAGDALENA", "GUAMAL META-META", "GUAMO-TOLIMA", "GUAPI-CAUCA", "GUAPOTA-SANTANDER", "GUARANDA-SUCRE", "GUARNE-ANTIOQUIA", "GUASCA-CUNDINAMARCA", "GUATAPE-ANTIOQUIA", "GUATAQUI-CUNDINAMARCA", "GUATAVITA-CUNDINAMARCA", "GUATEQUE-BOYACA", "GUATICA-RISALDA", "GUAVATA-SANTANDER", "GUAYABAL DE SIQUIMA-CUNDINAMARCA", "GUAYABETAL-CUNDINAMARCA", "GUAYATA-BOYACA", "GUEPSA-SANTANDER", "GUICAN-BOYACA", "GUTIERREZ-CUNDINAMARCA", "HACARI-NORTE DE SANTANDER", "HATILLO DE LOBA-BOLIVAR", "HATO COROZAL-CASANARE", "HATO-SANTANDER", "HATONUEVO-GUAJIRA", "HELICONIA-ANTIOQUIA", "HERRAN-NORTE DE SANTANDER", "HERRERA-TOLIMA", "HERVEO-TOLIMA", "HISPANIA-ANTIOQUIA", "HOBO-HUILA", "HONDA-TOLIMA", "IBAGUE-TOLIMA", "ICONONZO-TOLIMA", "IMUES-NARINO", "INIRIDA-GUAINIA", "INZA-CAUCA", "IPIALES-NARINO", "IQUIRA-HUILA", "ISNOS-HUILA", "ISTMINA-CHOCO", "ITAGUI-ANTIOQUIA", "ITUANGO-ANTIOQUIA", "IZA-BOYACA", "JAMBALO-CAUCA", "JAMUNDI-VALLE DEL CAUCA", "JARDIN-ANTIOQUIA", "JENESANO-BOYACA", "JERICO ANTIOQUIA-ANTIOQUIA", "JERICO BOYACA-BOYACA", "JERUSALEN-CUNDINAMARCA", "JESUS MARIA-SANTANDER", "JORDAN-SANTANDER", "JUAN DE ACOSTA-ATLANTICO", "JUNIN CUNDINAMARCA-CUNDINAMARCA", "LA APARTADA-CORDOBA", "LA ARADA-TOLIMA", "LA ARGENTINA-HUILA", "LA BELLEZA-SANTANDER", "LA CALERA-CUNDINAMARCA", "LA CAPILLA-BOYACA", "LA CEJA-ANTIOQUIA", "LA CELIA-RISALDA", "LA CHAPARRERA-CASANARE", "LA CHORRERA-AMAZONASONAS", "LA CRUZ-NARINO", "LA CUMBRE-VALLE DEL CAUCA", "LA DONJUANA-NORTE DE SANTANDER", "LA DORADA-CALDAS", "LA ESMERALDA-ARAUCA", "LA ESPERANZA-NORTE DE SANTANDER", "LA FLORIDA-NARINO", "LA GABARRA-NORTE DE SANTANDER", "LA GLORIA-CESAR", "LA GRAN VIA - ZONA BANANERA-MAGDALENA", "LA GRAN VÌA-CUNDINAMARCA", "LA HORMIGA /VALLE DEL GUAMUEZ-PUTUMAYOMAYO", "LA JAGUA DE IBIRICO-CESAR", "LA JAGUA DEL PILAR-GUAJIRA", "LA JULIA-META", "LA LIBERTAD-GUAVIARE", "LA LLANADA-NARINO", "LA MACARENA-META", "LA MERCED-CALDAS", "LA MESA-CUNDINAMARCA", "LA MONTANITA-CAQUETA", "LA PAILA-VALLE DEL CAUCA", "LA PALMA CUNDINAMARCA-CUNDINAMARCA", "LA PALMA GAMBITA-SANTANDER", "LA PAZ CESAR-CESAR", "LA PAZ SANTANDER-SANTANDER", "LA PENA-CUNDINAMARCA", "LA PINTADA-ANTIOQUIA", "LA PLATA-HUILA", "LA PLAYA-NORTE DE SANTANDER", "LA PRIMAVERA-VICHADA", "LA SALINA-CASANARE", "LA SIERRA CAUCA-CAUCA", "LA TEBAIDA-QUINDIO", "LA TOLA-NARINO", "LA UNION ANTIOQUIA-ANTIOQUIA", "LA UNION NARINO-NARINO", "LA UNION SUCRE-SUCRE", "LA UNION VALLE DEL CAUCA-VALLE DEL CAUCA", "LA UVITA-BOYACA", "LA VEGA CAUCA-CAUCA", "LA VEGA CUNDINAMARCA-CUNDINAMARCA", "LA VICTORIA BOYACA-BOYACA", "LA VICTORIA EL COLEGIO-CUNDINAMARCA", "LA VICTORIA VALLE DEL CAUCA-VALLE DEL CAUCA", "LA VIRGINIA-RISALDA", "LABATECA-NORTE DE SANTANDER", "LABRANZAGRANDE-BOYACA", "LANDAZURI-SANTANDER", "LEBRIJA-SANTANDER", "LEGUIZAMO-PUTUMAYOMAYO", "LEIVA-NARINO", "LEJANIAS-META", "LENGUAZAQUE-CUNDINAMARCA", "LERIDA-TOLIMA", "LETICIA-AMAZONASONAS", "LIBANO-TOLIMA", "LIBORINA-ANTIOQUIA", "LINARES-NARINO", "LLORENTE-NARINO", "LLORO-CHOCO", "LOPEZ-CAUCA", "LORICA-CORDOBA", "LOS ANDES-NARINO", "LOS CORDOBAS-CORDOBA", "LOS PALMITOS-SUCRE", "LOS PATIOS-NORTE DE SANTANDER", "LOS SANTOS-SANTANDER", "LOURDES-NORTE DE SANTANDER", "LURUACO-ATLANTICO", "MACANAL-BOYACA", "MACARAVITA-SANTANDER", "MACEO-ANTIOQUIA", "MACHETA-CUNDINAMARCA", "MADRID-CUNDINAMARCA", "MAGANGUE-BOLIVAR", "MAGUI-NARINO", "MAHATES-BOLIVAR", "MAICAO-GUAJIRA", "MAJAGUAL-SUCRE", "MALAGA-SANTANDER", "MALLAMA-NARINO", "MANATI-ATLANTICO", "MANAURE CESAR-CESAR", "MANAURE GUAJIRA-GUAJIRA", "MANI-CASANARE", "MANIZALES-CALDAS", "MANTA-CUNDINAMARCA", "MANZANARES-CALDAS", "MAPIRIPAN-META", "MARGARITA-BOLIVAR", "MARIA LA BAJA-BOLIVAR", "MARINILLA-ANTIOQUIA", "MARIPI-BOYACA", "MARIQUITA-TOLIMA", "MARMATO-CALDAS", "MARQUETALIA-CALDAS", "MARSELLA-RISALDA", "MARULANDA-CALDAS", "MATANZA-SANTANDER", "MAYA-CUNDINAMARCA", "MEDELLIN-ANTIOQUIA", "MEDINA-CUNDINAMARCA", "MEDIO ATRATO-CHOCO", "MEDIO BAUDO-CHOCO", "MEDIO SAN JUAN-CHOCO", "MELGAR-TOLIMA", "MERCADERES-CAUCA", "MESA DE LOS SANTOS -SANTANDER", "MESETAS-META", "MILAN-CAQUETA", "MIRAFLORES BOYACA-BOYACA", "MIRAFLORES GUAVIARE-GUAVIARE", "MIRANDA-CAUCA", "MISTRATO-RISALDA", "MITU-VAUPES", "MOCOA-PUTUMAYOMAYO", "MOGOTES-SANTANDER", "MOLAGAVITA-SANTANDER", "MOMIL-CORDOBA", "MOMPOS-BOLIVAR", "MONGUA-BOYACA", "MONGUI-BOYACA", "MONIQUIRA-BOYACA", "MONITOS-CORDOBA", "MONTEBELLO-ANTIOQUIA", "MONTECRISTO-BOLIVAR", "MONTELIBANO-CORDOBA", "MONTENEGRO-QUINDIO", "MONTERIA-CORDOBA", "MONTERREY-CASANARE", "MORALES BOLIVAR-BOLIVAR", "MORALES CAUCA-CAUCA", "MORELIA-CAQUETA", "MORROA-SUCRE", "MOSQUERA CUNDINAMARCA-CUNDINAMARCA", "MOSQUERA NARINO-NARINO", "MOTAVITA-BOYACA", "MURILLO-TOLIMA", "MURINDO-ANTIOQUIA", "MUTATA-ANTIOQUIA", "MUTISCUA-NORTE DE SANTANDER", "MUZO-BOYACA", "NARINO ANTIOQUIA-ANTIOQUIA", "NARINO CUNDINAMARCA-CUNDINAMARCA", "NARINO NARINO-NARINO", "NATAGA-HUILA", "NATAGAIMA-TOLIMA", "NAZARETH-CUNDINAMARCA", "NECHI-ANTIOQUIA", "NECOCLI-ANTIOQUIA", "NEIRA-CALDAS", "NEIVA-HUILA", "NEMOCON-CUNDINAMARCA", "NILO-CUNDINAMARCA", "NIMAIMA-CUNDINAMARCA", "NOBSA-BOYACA", "NOCAIMA-CUNDINAMARCA", "NORCASIA-CALDAS", "NOROSI BOLIVAR-BOLIVAR", "NOVITA-CHOCO", "NUEVA GRANADA-MAGDALENA", "NUEVO COLON-BOYACA", "NUNCHIA-CASANARE", "NUQUI-CHOCO", "OBANDO-VALLE DEL CAUCA", "OCAMONTE-SANTANDER", "OCANA-NORTE DE SANTANDER", "OIBA-SANTANDER", "OICATA-BOYACA", "OLIVAL-SANTANDER", "ONZAGA-SANTANDER", "OPORAPA-HUILA", "ORITO-PUTUMAYOMAYO", "OROCUE-CASANARE", "ORTEGA-TOLIMA", "OSPINA-NARINO", "OTANCHE-BOYACA", "OVEJAS-SUCRE", "PACHAQUIARO-META", "PACHAVITA-BOYACA", "PACHO-CUNDINAMARCA", "PACORA-CALDAS", "PADILLA-CAUCA", "PADUA-TOLIMA", "PAEZ BOYACA-BOYACA", "PAEZ CAUCA-CAUCA", "PAICOL-HUILA", "PAILITAS-CESAR", "PAIME-CUNDINAMARCA", "PAIPA-BOYACA", "PAJARITO-BOYACA", "PALERMO-HUILA", "PALESTINA HUILA-HUILA", "PALMAR DE VARELA-ATLANTICO", "PALMAR-SANTANDER", "PALMAS DEL SOCORRO-SANTANDER", "PALMIRA-VALLE DEL CAUCA", "PALMITO-SUCRE", "PALOCABILDO-TOLIMA", "PAMPLONA-NORTE DE SANTANDER", "PAMPLONITA-NORTE DE SANTANDER", "PANDI-CUNDINAMARCA", "PANQUEBA-BOYACA", "PARAMO-SANTANDER", "PARATEBUENO-CUNDINAMARCA", "PASCA-CUNDINAMARCA", "PASTO-NARINO", "PAUNA-BOYACA", "PAYA-BOYACA", "PAYANDE-TOLIMA", "PAZ DE ARIPORO-CASANARE", "PAZ DE RIO-BOYACA", "PEDRAZA-MAGDALENA", "PELAYA-CESAR", "PENOL-ANTIOQUIA", "PENSILVANIA-CALDAS", "PEQUE-ANTIOQUIA", "PEREIRA-RISALDA", "PESCA-BOYACA", "PIAMONTE-CAUCA", "PIEDECUESTA-SANTANDER", "PIEDRAS-TOLIMA", "PIENDAMO-CAUCA", "PIJAO-QUINDIO", "PIJINO DEL CARMEN-MAGDALENA", "PINCHOTE-SANTANDER", "PINILLOS-BOLIVAR", "PINALITO-META", "PIOJO-ATLANTICO", "PISBA-BOYACA", "PITALITO-HUILA", "PIVIJAY-MAGDALENA", "PLANADAS-TOLIMA", "PLANETA RICA-CORDOBA", "PLATO-MAGDALENA", "POLICARPA-NARINO", "POLONUEVO-ATLANTICO", "PONEDERA-ATLANTICO", "POPAYAN-CAUCA", "PORE-CASANARE", "POTOSI-NARINO", "PRADERA-VALLE DEL CAUCA", "PRADO-TOLIMA", "PROVIDENCIA NARINO-NARINO", "PUEBLO BELLO-CESAR", "PUEBLO NUEVO-CORDOBA", "PUEBLO RICO-RISALDA", "PUEBLORRICO-ANTIOQUIA", "PUEBLOVIEJO-MAGDALENA", "PUENTE NACIONAL-SANTANDER", "PUERRES-NARINO", "PUERTO ASIS-PUTUMAYOMAYO", "PUERTO BERRIO-ANTIOQUIA", "PUERTO BOYACA-BOYACA", "PUERTO CAICEDO-PUTUMAYOMAYO", "PUERTO CARRENO-VICHADA", "PUERTO COLOMBIA ATLANTICO-ATLANTICO", "PUERTO CONCORDIA-META", "PUERTO ESCONDIDO-CORDOBA", "PUERTO GAITAN-META", "PUERTO GUZMAN-PUTUMAYOMAYO", "PUERTO LIBERTADOR-CORDOBA", "PUERTO LLERAS-META", "PUERTO LOPEZ-META", "PUERTO NARE-ANTIOQUIA", "PUERTO PARRA-SANTANDER", "PUERTO RICO CAQUETA-CAQUETA", "PUERTO RICO META-META", "PUERTO RONDON-ARAUCA", "PUERTO SALGAR-CUNDINAMARCA", "PUERTO SANTANDER NORTE DE SANTANDER-NORTE DE SANTANDER", "PUERTO TEJADA-CAUCA", "PUERTO TRIUNFO-ANTIOQUIA", "PUERTO WILCHES-SANTANDER", "PULI-CUNDINAMARCA", "PUPIALES-NARINO", "PURACE-CAUCA", "PURIFICACION-TOLIMA", "PURISIMA-CORDOBA", "QUEBRADANEGRA-CUNDINAMARCA", "QUETAME-CUNDINAMARCA", "QUIBDO-CHOCO", "QUIMBAYA-QUINDIO", "QUINCHIA-RISALDA", "QUIPAMA-BOYACA", "QUIPILE-CUNDINAMARCA", "RAGONVALIA-NORTE DE SANTANDER", "RAMIRIQUI-BOYACA", "RAQUIRA-BOYACA", "RECETOR-CASANARE", "REGIDOR-BOLIVAR", "REMEDIOS-ANTIOQUIA", "REMOLINO MAGDALENA-MAGDALENA", "REMOLINO TAMINANGO-TAM-NARINO", "REPELON-ATLANTICO", "RESTREPO META-META", "RESTREPO VALLE DEL CAUCA-VALLE DEL CAUCA", "RETIRO-ANTIOQUIA", "RICAURTE CUNDINAMARCA-CUNDINAMARCA", "RICAURTE NARINO-NARINO", "RIO DE ORO-CESAR", "RIO QUITO-CHOCO", "RIO VIEJO-BOLIVAR", "RIOBLANCO-TOLIMA", "RIOFRIO-VALLE DEL CAUCA", "RIOHACHA-GUAJIRA", "RIONEGRO ANTIOQUIA-ANTIOQUIA", "RIONEGRO SANTANDER-SANTANDER", "RIOSUCIO CALDAS-CALDAS", "RIOSUCIO CHOCO-CHOCO", "RISARALDA-CALDAS", "RIVERA-HUILA", "ROBERTO PAYAN-NARINO", "ROLDANILLO-VALLE DEL CAUCA", "RONCESVALLES-TOLIMA", "RONDON-BOYACA", "ROSAS-CAUCA", "ROVIRA-TOLIMA", "SABANA DE TORRES-SANTANDER", "SABANAGRANDE-ATLANTICO", "SABANALARGA ANTIOQUIA-ANTIOQUIA", "SABANALARGA ATLANTICO-ATLANTICO", "SABANALARGA CASANARE-CASANARE", "SABANAS DE SAN ANGEL-MAGDALENA", "SABANETA-ANTIOQUIA", "SABOYA-BOYACA", "SACAMA-CASANARE", "SACHICA-BOYACA", "SAHAGUN-CORDOBA", "SALADOBLANCO-HUILA", "SALAMINA CALDAS-CALDAS", "SALAMINA MAGDALENA-MAGDALENA", "SALAZAR-NORTE DE SANTANDER", "SALDANA-TOLIMA", "SALENTO-QUINDIO", "SALGAR-ANTIOQUIA", "SAMACA-BOYACA", "SAMANA-CALDAS", "SAMANIEGO-NARINO", "SAMPUES-SUCRE", "SAN AGUSTIN-HUILA", "SAN ALBERTO-CESAR", "SAN ANDRES ARCHIPIELAGO DE SAN ANDRES , PROVIDENCIA Y SANTA CATALINA-ARCH", "SAN ANDRES DE CUERQUIA-ANTIOQUIA", "SAN ANDRES DE SOTAVENTO-CORDOBA", "SAN ANDRES SANTANDER-SANTANDER", "SAN ANTERO-CORDOBA", "SAN ANTONIO DEL TEQUENDAMA-CUNDINAMARCA", "SAN ANTONIO-TOLIMA", "SAN BENITO ABAD-SUCRE", "SAN BENITO-SANTANDER", "SAN BERNARDO CUNDINAMARCA-CUNDINAMARCA", "SAN BERNARDO DEL VIENTO-CORDOBA", "SAN BERNARDO NARINO-NARINO", "SAN CALIXTO-NORTE DE SANTANDER", "SAN CARLOS ANTIOQUIA-ANTIOQUIA", "SAN CARLOS CORDOBA-CORDOBA", "SAN CARLOS DE GUAROA-META", "SAN CAYETANO CUNDINAMARCA-CUNDINAMARCA", "SAN CAYETANO NORTE DE SANTANDER-NORTE DE SANTANDER", "SAN CRISTOBAL-BOLIVAR", "SAN DIEGO-CESAR", "SAN EDUARDO-BOYACA", "SAN ESTANISLAO-BOLIVAR", "SAN FELIX-CALDAS", "SAN FERNANDO-BOLIVAR", "SAN FRANCISCO ANTIOQUIA-ANTIOQUIA", "SAN FRANCISCO CUNDINAMARCA-CUNDINAMARCA", "SAN FRANCISCO PUTUMAYO-PUTUMAYOMAYO", "SAN GIL-SANTANDER", "SAN JACINTO DEL CAUCA-BOLIVAR", "SAN JACINTO-BOLIVAR", "SAN JERONIMO-ANTIOQUIA", "SAN JOAQUIN-SANTANDER", "SAN JOSE DE LA MONTANA-ANTIOQUIA", "SAN JOSE DE MIRANDA-SANTANDER", "SAN JOSE DE PARE-BOYACA", "SAN JOSE DE URE-CORDOBA", "SAN JOSE DEL FRAGUA-CAQUETA", "SAN JOSE DEL GUAVIARE-GUAVIARE", "SAN JOSE DEL PALMAR-CHOCO", "SAN JOSE-CALDAS", "SAN JUAN DE ARAMA-META", "SAN JUAN DE BETULIA-SUCRE", "SAN JUAN DE RIO SECO-CUNDINAMARCA", "SAN JUAN DE URABA-ANTIOQUIA", "SAN JUAN DEL CESAR-GUAJIRA", "SAN JUAN NEPOMUCENO-BOLIVAR", "SAN JUANITO-META", "SAN LORENZO-NARINO", "SAN LUIS ANTIOQUIA-ANTIOQUIA", "SAN LUIS DE GACENO-BOYACA", "SAN LUIS DE PALENQUE-CASANARE", "SAN LUIS TOLIMA-TOLIMA", "SAN MARCOS-SUCRE", "SAN MARTIN CESAR-CESAR", "SAN MARTIN DE LOBA-BOLIVAR", "SAN MARTIN META-META", "SAN MATEO-BOYACA", "SAN MIGUEL DE SEMA-BOYACA", "SAN MIGUEL/ LA DORADA-PUTUMAYOMAYO", "SAN MIGUEL-SANTANDER", "SAN ONOFRE-SUCRE", "SAN PABLO BOLIVAR-BOLIVAR", "SAN PABLO DE BORBUR-BOYACA", "SAN PABLO NARINO-NARINO", "SAN PEDRO ANTIOQUIA-ANTIOQUIA", "SAN PEDRO DE CARTAGO-NARINO", "SAN PEDRO DE URABA-ANTIOQUIA", "SAN PEDRO SUCRE-SUCRE", "SAN PEDRO VALLE DEL CAUCA-VALLE DEL CAUCA", "SAN PELAYO-CORDOBA", "SAN RAFAEL-ANTIOQUIA", "SAN ROQUE-ANTIOQUIA", "SAN SEBASTIAN DE BUENAVISTA-MAGDALENA", "SAN SEBASTIAN-CAUCA", "SAN VICENTE DE CHUCURI-SANTANDER", "SAN VICENTE DEL CAGUAN-CAQUETA", "SAN VICENTE-ANTIOQUIA", "SAN ZENON-MAGDALENA", "SANDONA-NARINO", "SANTA ANA-MAGDALENA", "SANTA BARBARA ANTIOQUIA-ANTIOQUIA", "SANTA BARBARA DE PINTO-MAGDALENA", "SANTA BARBARA NARINO-NARINO", "SANTA BARBARA SANTANDER-SANTANDER", "SANTA CATALINA-BOLIVAR", "SANTA HELENA DEL OPON-SANTANDER", "SANTA ISABEL-TOLIMA", "SANTA LUCIA-ATLANTICO", "SANTA MARIA BOYACA-BOYACA", "SANTA MARIA HUILA-HUILA", "SANTA MARTA-MAGDALENA", "SANTA ROSA DE CABAL-RISALDA", "SANTA ROSA DE LIMA-BOLIVAR", "SANTA ROSA DE OSOS-ANTIOQUIA", "SANTA ROSA DE VITERBO-BOYACA", "SANTA ROSA DEL SUR-BOLIVAR", "SANTA ROSA-CAUCA", "SANTA ROSALIA-VICHADA", "SANTA SOFIA-BOYACA", "SANTACRUZ-NARINO", "SANTAFE DE ANTIOQUIA-ANTIOQUIA", "SANTANA-BOYACA", "SANTANDER DE QUILICHAO-CAUCA", "SANTIAGO NORTE DE SANTANDER-NORTE DE SANTANDER", "SANTIAGO PEREZ-TOLIMA", "SANTIAGO PUTUMAYO-PUTUMAYOMAYO", "SANTO DOMINGO-ANTIOQUIA", "SANTO TOMAS-ATLANTICO", "SANTUARIO-RISALDA", "SAPUYES-NARINO", "SARAVENA-ARAUCA", "SARDINATA-NORTE DE SANTANDER", "SASAIMA-CUNDINAMARCA", "SATIVANORTE-BOYACA", "SATIVASUR-BOYACA", "SEGOVIA-ANTIOQUIA", "SESQUILE-CUNDINAMARCA", "SEVILLA VALLE DEL CAUCA-VALLE DEL CAUCA", "SIACHOQUE-BOYACA", "SIBATE-CUNDINAMARCA", "SIBUNDOY-PUTUMAYOMAYO", "SILOS-NORTE DE SANTANDER", "SILVANIA-CUNDINAMARCA", "SILVIA-CAUCA", "SIMACOTA-SANTANDER", "SIMIJACA-CUNDINAMARCA", "SIMITI-BOLIVAR", "SINCE-SUCRE", "SINCELEJO-SUCRE", "SITIONUEVO-MAGDALENA", "SOACHA-CUNDINAMARCA", "SOATA-BOYACA", "SOCHA-BOYACA", "SOCORRO-SANTANDER", "SOCOTA-BOYACA", "SOGAMOSO-BOYACA", "SOLANO-CAQUETA", "SOLEDAD-ATLANTICO", "SOLITA-CAQUETA", "SOMONDOCO-BOYACA", "SONSON-ANTIOQUIA", "SOPETRAN-ANTIOQUIA", "SOPLAVIENTO-BOLIVAR", "SOPO-CUNDINAMARCA", "SORA-BOYACA", "SORACA-BOYACA", "SOTAQUIRA-BOYACA", "SOTARA-CAUCA", "SUAITA-SANTANDER", "SUAN-ATLANTICO", "SUAREZ CAUCA-CAUCA", "SUAREZ TOLIMA-TOLIMA", "SUAZA-HUILA", "SUBACHOQUE-CUNDINAMARCA", "SUCRE CAUCA-CAUCA", "SUCRE SANTANDER-SANTANDER", "SUCRE SUCRE-SUCRE", "SUESCA-CUNDINAMARCA", "SUPATA-CUNDINAMARCA", "SUPIA-CALDAS", "SURATA-SANTANDER", "SUSA-CUNDINAMARCA", "SUSACON-BOYACA", "SUTAMARCHAN-BOYACA", "SUTATAUSA-CUNDINAMARCA", "SUTATENZA-BOYACA", "TABIO-CUNDINAMARCA", "TADO-CHOCO", "TALAIGUA NUEVO-BOLIVAR", "TAMALAMEQUE-CESAR", "TAMARA-CASANARE", "TAME-ARAUCA", "TAMESIS-ANTIOQUIA", "TAMINANGO-NARINO", "TANGUA-NARINO", "TARAIRA-VAUPES", "TARAZA-ANTIOQUIA", "TARQUI-HUILA", "TARSO-ANTIOQUIA", "TASCO-BOYACA", "TAURAMENA-CASANARE", "TAUSA-CUNDINAMARCA", "TELLO-HUILA", "TENERIFE-MAGDALENA", "TENJO-CUNDINAMARCA", "TENZA-BOYACA", "TEORAMA-NORTE DE SANTANDER", "TERUEL-HUILA", "TESALIA-HUILA", "TIBACUY-CUNDINAMARCA", "TIBANA-BOYACA", "TIBASOSA-BOYACA", "TIBIRITA-CUNDINAMARCA", "TIBU-NORTE DE SANTANDER", "TIERRALTA-CORDOBA", "TIMANA-HUILA", "TIMBIO-CAUCA", "TIMBIQUI-CAUCA", "TINJACA-BOYACA", "TIPACOQUE-BOYACA", "TIQUISIO NUEVO-BOLIVAR", "TITIRIBI-ANTIOQUIA", "TOBIA-CUNDINAMARCA", "TOCA-BOYACA", "TOCAIMA-CUNDINAMARCA", "TOCANCIPA-CUNDINAMARCA", "TOGUI-BOYACA", "TOLEDO ANTIOQUIA-ANTIOQUIA", "TOLEDO NORTE DE SANTANDER-NORTE DE SANTANDER", "TOLU VIEJO-SUCRE", "TOLU-SUCRE", "TONA-SANTANDER", "TOPAGA-BOYACA", "TOPAIPI-CUNDINAMARCA", "TORIBIO-CAUCA", "TORO-VALLE DEL CAUCA", "TOTA-BOYACA", "TOTORO-CAUCA", "TRINIDAD-CASANARE", "TRUJILLO-VALLE DEL CAUCA", "TUBARA-ATLANTICO", "TUCHIN-CORDOBA", "TULUA-VALLE DEL CAUCA", "TUMACO-NARINO", "TUNJA-BOYACA", "TUNUNGUA-BOYACA", "TUQUERRES-NARINO", "TURBACO-BOLIVAR", "TURBANA-BOLIVAR", "TURBO-ANTIOQUIA", "TURMEQUE-BOYACA", "TUTA-BOYACA", "TUTAZA-BOYACA", "UBALA-CUNDINAMARCA", "UBAQUE-CUNDINAMARCA", "UBATE-CUNDINAMARCA", "ULLOA-VALLE DEL CAUCA", "UMBITA-BOYACA", "UNE-CUNDINAMARCA", "UNGUIA-CHOCO", "UNION PANAMERICANA-CHOCO", "URAMITA-ANTIOQUIA", "URIBE-META", "URIBIA-GUAJIRA", "URRAO-ANTIOQUIA", "URUMITA-GUAJIRA", "USIACURI-ATLANTICO", "UTICA-CUNDINAMARCA", "VADO REAL-SANTANDER", "VALDIVIA-ANTIOQUIA", "VALENCIA-CORDOBA", "VALLE DE SAN JOSE-SANTANDER", "VALLE DE SAN JUAN-TOLIMA", "VALLEDUPAR-CESAR", "VALPARAISO ANTIOQUIA-ANTIOQUIA", "VALPARAISO CAQUETA-CAQUETA", "VEGACHI-ANTIOQUIA", "VELEZ-SANTANDER", "VENADILLO-TOLIMA", "VENECIA ANTIOQUIA-ANTIOQUIA", "VENECIA CUNDINAMARCA-CUNDINAMARCA", "VENTAQUEMADA-BOYACA", "VERGARA-CUNDINAMARCA", "VERSALLES MEDELLIN-ANTIOQUIA", "VERSALLES VALLE DEL CAUCA-VALLE DEL CAUCA", "VETAS-SANTANDER", "VIANI-CUNDINAMARCA", "VICTORIA-CALDAS", "VIGIA DEL FUERTE-ANTIOQUIA", "VIJES-VALLE DEL CAUCA", "VILLA CARO-NORTE DE SANTANDER", "VILLA DE LEYVA-BOYACA", "VILLA DEL ROSARIO-NORTE DE SANTANDER", "VILLA RICA-CAUCA", "VILLAGARZON-PUTUMAYOMAYO", "VILLAGOMEZ-CUNDINAMARCA", "VILLAHERMOSA-TOLIMA", "VILLAMARIA-CALDAS", "VILLANUEVA BOLIVAR-BOLIVAR", "VILLANUEVA CASANARE-CASANARE", "VILLANUEVA GUAJIRA-GUAJIRA", "VILLANUEVA SANTANDER-SANTANDER", "VILLAPINZON-CUNDINAMARCA", "VILLARRICA-TOLIMA", "VILLAVICENCIO-META", "VILLAVIEJA-HUILA", "VILLETA-CUNDINAMARCA", "VIOTA-CUNDINAMARCA", "VIRACACHA-BOYACA", "VISTAHERMOSA-META", "VITERBO-CALDAS", "YACOPI-CUNDINAMARCA", "YACUANQUER-NARINO", "YAGUARA-HUILA", "YALI-ANTIOQUIA", "YARUMAL-ANTIOQUIA", "YOLOMBO-ANTIOQUIA", "YONDO-ANTIOQUIA", "YOPAL-CASANARE", "YOTOCO-VALLE DEL CAUCA", "YUMBO-VALLE DEL CAUCA", "ZAMBRANO-BOLIVAR", "ZAPATOCA-SANTANDER", "ZARAGOZA-ANTIOQUIA", "ZARZAL-VALLE DEL CAUCA", "ZETAQUIRA-BOYACA", "ZIPACON-CUNDINAMARCA", "ZIPAQUIRA-CUNDINAMARCA", "ZONA BANANERA-MAGDALENA"};
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_formulario);
        StrictMode.ThreadPolicy politicas = new StrictMode.ThreadPolicy.Builder().permitAll().build();
        StrictMode.setThreadPolicy(politicas);
        Button btRegresar = (Button) findViewById(R.id.btnRegresar);
        Button btEnviar = (Button) findViewById(R.id.btnEnviar);
        tvCiudad = (TextView) findViewById(R.id.txtCiudadR);
        tvDireccion = (TextView) findViewById(R.id.txtDireccionR);
        tvNombre = (TextView) findViewById(R.id.txtNombreR);
        tvTelefono = (TextView) findViewById(R.id.txtTelefonoR);
        tvPeso = (TextView) findViewById(R.id.txtPesoAprox);

        btRegresar.setOnClickListener(this);
        btEnviar.setOnClickListener(this);
        tvCiudad.setOnClickListener(this);
        tvDireccion.setOnTouchListener(this);
        tvNombre.setOnTouchListener(this);
        tvTelefono.setOnTouchListener(this);
        tvPeso.setOnTouchListener(this);

        // Rellene de Spinner Tipo de Envio
        tipoEnvio = (Spinner) findViewById(R.id.spTipoEnvio);
        ArrayAdapter<String> adaptadorTipoEnvio = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_item, arraytipoEnvio);
        tipoEnvio.setAdapter(adaptadorTipoEnvio);

        //Rellenar Spiner Ciudad
        ciudadDestino = (Spinner) findViewById(R.id.spCiudad);
        ArrayAdapter<String> adaptadorCiudad = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_item, arrayCiudadDestino);
        ciudadDestino.setAdapter(adaptadorCiudad);

        // Capturamos la Seleccion de Tipo Envio
        tipoEnvio.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                switch (position)
                {
                    case 0:
                        //Toast.makeText(getBaseContext(),"Debe Seleccionar un tipo de Envio", Toast.LENGTH_LONG).show();
                        seleccionTipoEnvio = false;
                        break;
                    case 1:
                        SeleccionTipoEnvio = arraytipoEnvio[position];
                        seleccionTipoEnvio = true;
                        break;
                    case 2:
                        SeleccionTipoEnvio = arraytipoEnvio[position];
                        seleccionTipoEnvio = true;
                        break;
                    case 3:
                        SeleccionTipoEnvio = arraytipoEnvio[position];
                        seleccionTipoEnvio = true;
                        break;
                    case 4:
                        SeleccionTipoEnvio = arraytipoEnvio[position];
                        seleccionTipoEnvio = true;
                        break;
                    case 5:
                        SeleccionTipoEnvio = arraytipoEnvio[position];
                        seleccionTipoEnvio = true;
                        break;
                    case 6:
                        SeleccionTipoEnvio = arraytipoEnvio[position];
                        seleccionTipoEnvio = true;
                        break;
                }
            }
            @Override
            public void onNothingSelected(AdapterView<?> parent) {
                //Toast.makeText(getBaseContext(),"Debe Seleccionar un tipo de Envio", Toast.LENGTH_LONG).show();
            }
        });

        // Capturamos la Seleccion de Ciudad
        ciudadDestino.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                if(position == 0)
                {
                    seleccionDestino = false;
                }else{
                    SeleccionCiudadDestino = arrayCiudadDestino[position];
                    seleccionDestino = true;
                }
                Toast.makeText(getBaseContext(), SeleccionCiudadDestino, Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onNothingSelected(AdapterView<?> parent) {

            }
        });
    }

    @Override
    public void onClick(View v) {
        switch (v.getId())
        {
            case R.id.btnRegresar:
                touchDireccion = false;
                touchNombre = false;
                touchTelefono = false;
                touchPeso = false;
                Toast.makeText(getBaseContext(),"Proceso de Recogida Cancelado", Toast.LENGTH_SHORT).show();
                Intent regresar_Activity = new Intent(formulario.this, main_Recogeme.class);
                startActivity(regresar_Activity);
                finish();
                break;
            case R.id.btnEnviar:
                touchDireccion = false;
                touchNombre = false;
                touchTelefono = false;
                touchPeso = false;
                if((tvNombre.getText().length() > 5) && (tvDireccion.getText().length() > 5) && (tvTelefono.getText().length() > 1) && (seleccionDestino != false) && (seleccionTipoEnvio != false))
                {
                    Toast.makeText(getBaseContext(),"Sin Errores", Toast.LENGTH_SHORT).show();
                    try
                    {
                        Log.v("myTag", "boton Enviar Presionado");
                        String dato = handler.agregar(main_Recogeme.correo,tvCiudad.getText().toString(), tvNombre.getText().toString(),                                                  Integer.parseInt(tvTelefono.getText().toString()), tvDireccion.getText().toString(),SeleccionCiudadDestino,                                                       SeleccionTipoEnvio, Integer.parseInt(tvPeso.getText().toString()));
                        Log.v("myTag", dato);

                        popUp();
                    }
                    catch (Exception e)
                    {
                        Log.v("myTag", "Error Base datos");
                    }
                    enviar_Notificacion_pendiente();
                }
                else{
                    Toast.makeText(getBaseContext(), "diligencie todos los Datos", Toast.LENGTH_SHORT).show();
                }

                startService(new Intent(this, Servicio_Notificacion.class));


                break;
            case R.id.txtCiudadR:
                Toast.makeText(getBaseContext(), "Actualmente el Servicio de Recogidas Solo esta Habilitado Para la Ciudad de Cali", Toast.LENGTH_SHORT).show();
                break;

        }
    }

    @Override
    public boolean onTouch(View v, MotionEvent event) {
        switch (v.getId())
        {
            case R.id.txtDireccionR:
                if(!touchDireccion)tvDireccion.setText(null);
                tvDireccion.setTextColor(tvDireccion.getContext().getResources().getColor(R.color.Gris_Oscuro));
                touchDireccion = true;
                break;
            case R.id.txtNombreR:
                if(!touchNombre)tvNombre.setText(null);
                tvNombre.setTextColor(tvNombre.getContext().getResources().getColor(R.color.Gris_Oscuro));
                touchNombre = true;
                break;
            case R.id.txtTelefonoR:
                if(!touchTelefono)tvTelefono.setText(null);
                tvTelefono.setTextColor(tvTelefono.getContext().getResources().getColor(R.color.Gris_Oscuro));
                touchTelefono = true;
                break;
            case R.id.txtPesoAprox:
                if(!touchPeso)tvPeso.setText(null);
                tvPeso.setTextColor(tvPeso.getContext().getResources().getColor(R.color.Gris_Oscuro));
                touchPeso = true;
                break;
        }
        return false;
    }


    public void popUp(){
        AlertDialog.Builder builder = new AlertDialog.Builder(this);
        builder.setMessage("Datos Enviados Exitosamente, antes de las 6:00pm sera recogido su  encomienda")
                .setTitle("Proceso Exitoso")
                .setCancelable(false)
                .setNeutralButton("Aceptar",
                        new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialog, int id) {
                                dialog.cancel();
                                Toast.makeText(getBaseContext(), "Proceso de Recogida Cancelado", Toast.LENGTH_SHORT).show();
                                Intent regresar_Activity = new Intent(formulario.this, main_Recogeme.class);
                                startActivity(regresar_Activity);
                                finish();
                            }
                        });
        AlertDialog alert = builder.create();
        alert.show();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        // TODO Auto-generated method stub
        if (keyCode == event.KEYCODE_BACK) {
            Toast.makeText(getBaseContext(),"Proceso de Recogida Cancelado", Toast.LENGTH_SHORT).show();
            Intent regresar_Activity = new Intent(formulario.this, main_Recogeme.class);
            startActivity(regresar_Activity);
            finish();
        }
        return super.onKeyDown(keyCode, event);
    }

    // Notificacion
    public void enviar_Notificacion_pendiente(){
        notificacion_Pendiente = (NotificationManager)getSystemService(NOTIFICATION_SERVICE);
        Notification notificacion_Pendiente_NT = new Notification(R.drawable.recogeme_main2,"Información Transmitida", System.currentTimeMillis());
        PendingIntent intencionPendiente=PendingIntent.getActivity(getApplicationContext(),0,new Intent(getApplicationContext(),listado.class),0);

        notificacion_Pendiente_NT.setLatestEventInfo(getApplicationContext(),"Localizando Mensajeros", "Tu Recogidad se esta transmitiendo a un mensajero", intencionPendiente);

        notificacion_Pendiente.notify(ID_Notif_Pendiente, notificacion_Pendiente_NT);
    }

}
